---
title: "Shiny objects and tests"
author: "Matthieu Huy"
date: "2023-02-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(raster)
library(janitor)
library(here)
library(rgdal)
library(sf)
library(tidyverse)
library(tmap)
```

```{r}
state_sf <- read_sf(here("data/tl_2022_us_state/tl_2022_us_state.shp")) |>
  clean_names()

county_sf <- read_sf(here("data/tl_2022_us_county/tl_2022_us_county.shp")) |>
  clean_names() |>
  filter(statefp != c("02", "15")) ### exclude Alaska and Hawaii, not incuded in prison data

superfund_csv <- read_csv(here("data/superfund_data/superfund_data_updated.csv")) |>
  clean_names()

superfund_sf <- st_as_sf(superfund_csv,
                         coords = c("longitude", "latitude"))

#st_crs(county_sf) ### EPSG 4296
#st_crs(superfund_sf) ### no crs

superfund_sf <- st_set_crs(superfund_sf, st_crs(county_sf))

#st_crs(superfund_sf) ### EPSG 4296

superfund_buffers_1m_sf <- read_sf(here("data/superfund_data/active_sites_1.shp"))
superfund_buffers_3m_sf <- read_sf(here("data/superfund_data/active_sites_3mile.shp"))
prison_boundaries_1_8_csv <- read_csv(here("data/superfund_data/active_1_8mile_buffer.csv")) |>
  clean_names()
prison_boundaries_sf <- read_sf(here("data/Prison_Boundaries/Prison_Boundaries.shp")) |>
  clean_names() 

prison_boundaries_sf$county <- str_to_title(prison_boundaries_sf$county)

#prison_boundaries_1_8sf <- st_as_sf(prison_boundaries_1_8_csv,
        #                           coords = c("Longitude", "Latitude"))

superfund_buffers_3m_sf <- st_set_crs(superfund_buffers_3m_sf, st_crs(county_sf))
prison_boundaries_sf <- st_set_crs(prison_boundaries_sf, st_crs(county_sf))

choices <- prison_boundaries_sf |>
      filter(state == "PA") |>
      pull(county)

state_names <- state_sf |>
  as.data.frame() |>
  select(statefp, state = name) 
county_state_names_df <- county_sf |>
  as.data.frame() |>
  select(statefp, countyfp, county = name) |>
  inner_join(state_names, by = c("statefp")) |>
  mutate(countyfips = paste(statefp, countyfp, sep = "")) |>
  select(county, state, countyfips)
county_state_names_sf <- county_sf |>
  select(statefp, countyfp, county = name) |>
  inner_join(state_names, by = c("statefp")) |>
  mutate(countyfips = paste(statefp, countyfp, sep = "")) |>
  select(county, state, countyfips)

prison_boundaries_sf <- prison_boundaries_sf |>
  select(-c("state", "county")) |>
  inner_join(county_state_names_df, by = c("countyfips")) 

county_filtered <- county_state_names_sf |>
      filter(state == state_input) |>
      filter(name == county_input) 
```

```{r}
tmap_mode(mode = "view")

tm_shape(superfund_buffers_3m_sf) +
  tm_fill(col = "red",
          alpha = 0.3) +
  tm_polygons() +
tm_shape(superfund_buffers_1m_sf) +
  tm_fill(col = "darkred",
          alpha = 0.3) +
  tm_polygons() +
tm_shape(prison_boundaries_sf) +
  tm_dots("name",
          palette = "Reds",
          legend.show = FALSE)
```


```{r}
### precip rasters region 1 ###########################

pr_1a <- raster(here("data/climate_scenarios/lasso_data_1/LOCA_rcp85_eparegion1_CMCC-CMS_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_1b <- raster(here("data/climate_scenarios/lasso_data_1/LOCA_rcp85_eparegion1_GFDL-ESM2G_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_1c <- raster(here("data/climate_scenarios/lasso_data_1/LOCA_rcp85_eparegion1_HadGEM2-CC_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_1d <- raster(here("data/climate_scenarios/lasso_data_1/LOCA_rcp85_eparegion1_inmcm4_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_1e <- raster(here("data/climate_scenarios/lasso_data_1/LOCA_rcp85_eparegion1_MIROC-ESM_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_1f <- raster(here("data/climate_scenarios/lasso_data_1/LOCA_rcp85_eparegion1_MIROC-ESM-CHEM_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr1_stack <- stack(pr_1a, pr_1b, pr_1c, pr_1d, pr_1e, pr_1f) # Put all pr rasters in a stack

pr1_raster_avg <- calc(pr1_stack, mean) #avg all climate models to generate 1 "mean" raster layer

### temp rasters region 1 ###########################

temp_1a <- raster(here("data/climate_scenarios/lasso_data_1/LOCA_rcp85_eparegion1_CMCC-CMS_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_1b <- raster(here("data/climate_scenarios/lasso_data_1/LOCA_rcp85_eparegion1_GFDL-ESM2G_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_1c <- raster(here("data/climate_scenarios/lasso_data_1/LOCA_rcp85_eparegion1_HadGEM2-CC_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_1d <- raster(here("data/climate_scenarios/lasso_data_1/LOCA_rcp85_eparegion1_inmcm4_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_1e <- raster(here("data/climate_scenarios/lasso_data_1/LOCA_rcp85_eparegion1_MIROC-ESM_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_1f <- raster(here("data/climate_scenarios/lasso_data_1/LOCA_rcp85_eparegion1_MIROC-ESM-CHEM_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp1_stack <- stack(temp_1a, temp_1b, temp_1c, temp_1d, temp_1e, temp_1f) # Put all pr rasters in a stack

temp1_raster_avg <- calc(temp1_stack, mean) #avg all climate models to generate 1 "mean" raster layer

### precip rasters region 2 ###########################

pr_2a <- raster(here("data/climate_scenarios/lasso_data_2/LOCA_rcp85_eparegion2_CMCC-CMS_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_2b <- raster(here("data/climate_scenarios/lasso_data_2/LOCA_rcp85_eparegion2_GFDL-ESM2M_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_2c <- raster(here("data/climate_scenarios/lasso_data_2/LOCA_rcp85_eparegion2_GISS-E2-R_r2i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_2d <- raster(here("data/climate_scenarios/lasso_data_2/LOCA_rcp85_eparegion2_HadGEM2-CC_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_2e <- raster(here("data/climate_scenarios/lasso_data_2/LOCA_rcp85_eparegion2_inmcm4_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_2f <- raster(here("data/climate_scenarios/lasso_data_2/LOCA_rcp85_eparegion2_MIROC-ESM_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_2g <- raster(here("data/climate_scenarios/lasso_data_2/LOCA_rcp85_eparegion2_MIROC-ESM-CHEM_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_2h <- raster(here("data/climate_scenarios/lasso_data_2/LOCA_rcp85_eparegion2_MPI-ESM-MR_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr2_stack <- stack(pr_2a, pr_2b, pr_2c, pr_2d, pr_2e, pr_2f, pr_2g, pr_2h) # Put all pr rasters in a stack

pr2_raster_avg <- calc(pr2_stack, mean) #avg all climate models to generate 1 "mean" raster layer

### temp rasters region 2 ###########################

temp_2a <- raster(here("data/climate_scenarios/lasso_data_2/LOCA_rcp85_eparegion2_CMCC-CMS_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

temp_2b <- raster(here("data/climate_scenarios/lasso_data_2/LOCA_rcp85_eparegion2_GFDL-ESM2M_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

temp_2c <- raster(here("data/climate_scenarios/lasso_data_2/LOCA_rcp85_eparegion2_GISS-E2-R_r2i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

temp_2d <- raster(here("data/climate_scenarios/lasso_data_2/LOCA_rcp85_eparegion2_HadGEM2-CC_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

temp_2e <- raster(here("data/climate_scenarios/lasso_data_2/LOCA_rcp85_eparegion2_inmcm4_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

temp_2f <- raster(here("data/climate_scenarios/lasso_data_2/LOCA_rcp85_eparegion2_MIROC-ESM_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

temp_2g <- raster(here("data/climate_scenarios/lasso_data_2/LOCA_rcp85_eparegion2_MIROC-ESM-CHEM_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

temp_2h <- raster(here("data/climate_scenarios/lasso_data_2/LOCA_rcp85_eparegion2_MPI-ESM-MR_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

temp2_stack <- stack(temp_2a, temp_2b, temp_2c, temp_2d, temp_2e, temp_2f, temp_2g, temp_2h) # Put all pr rasters in a stack

temp2_raster_avg <- calc(temp2_stack, mean) #avg all climate models to generate 1 "mean" raster layer


### precip rasters region 3 ###########################

pr_3a <- raster(here("data/climate_scenarios/lasso_data_3/LOCA_rcp85_eparegion3_GFDL-CM3_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_3b <- raster(here("data/climate_scenarios/lasso_data_3/LOCA_rcp85_eparegion3_HadGEM2-CC_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_3c <- raster(here("data/climate_scenarios/lasso_data_3/LOCA_rcp85_eparegion3_HadGEM2-ES_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_3d <- raster(here("data/climate_scenarios/lasso_data_3/LOCA_rcp85_eparegion3_inmcm4_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_3e <- raster(here("data/climate_scenarios/lasso_data_3/LOCA_rcp85_eparegion3_IPSL-CM5A-LR_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_3f <- raster(here("data/climate_scenarios/lasso_data_3/LOCA_rcp85_eparegion3_MIROC-ESM_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_3g <- raster(here("data/climate_scenarios/lasso_data_3/LOCA_rcp85_eparegion3_MPI-ESM-MR_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_3h <- raster(here("data/climate_scenarios/lasso_data_3/LOCA_rcp85_eparegion3_MRI-CGCM3_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr3_stack <- stack(pr_3a, pr_3b, pr_3c, pr_3d, pr_3e, pr_3f, pr_3g, pr_3h) # Put all pr rasters in a stack

pr3_raster_avg <- calc(pr3_stack, mean) #avg all climate models to generate 1 "mean" raster layer

### temp rasters region 3 ###########################

temp_3a <- raster(here("data/climate_scenarios/lasso_data_3/LOCA_rcp85_eparegion3_GFDL-CM3_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

temp_3b <- raster(here("data/climate_scenarios/lasso_data_3/LOCA_rcp85_eparegion3_HadGEM2-CC_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

temp_3c <- raster(here("data/climate_scenarios/lasso_data_3/LOCA_rcp85_eparegion3_HadGEM2-ES_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

temp_3d <- raster(here("data/climate_scenarios/lasso_data_3/LOCA_rcp85_eparegion3_inmcm4_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

temp_3e <- raster(here("data/climate_scenarios/lasso_data_3/LOCA_rcp85_eparegion3_IPSL-CM5A-LR_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

temp_3f <- raster(here("data/climate_scenarios/lasso_data_3/LOCA_rcp85_eparegion3_MIROC-ESM_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

temp_3g <- raster(here("data/climate_scenarios/lasso_data_3/LOCA_rcp85_eparegion3_MPI-ESM-MR_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

temp_3h <- raster(here("data/climate_scenarios/lasso_data_3/LOCA_rcp85_eparegion3_MRI-CGCM3_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

temp3_stack <- stack(temp_3a, temp_3b, temp_3c, temp_3d, temp_3e, temp_3f, temp_3g, temp_3h) # Put all pr rasters in a stack

temp3_raster_avg <- calc(temp3_stack, mean) #avg all climate models to generate 1 "mean" raster layer

### precip rasters region 4 ###########################

pr_4a <- raster(here("data/climate_scenarios/lasso_data_4/LOCA_rcp85_eparegion4_FGOALS-g2_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_4b <- raster(here("data/climate_scenarios/lasso_data_4/LOCA_rcp85_eparegion4_GFDL-CM3_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_4c <- raster(here("data/climate_scenarios/lasso_data_4/LOCA_rcp85_eparegion4_HadGEM2-CC_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_4d <- raster(here("data/climate_scenarios/lasso_data_4/LOCA_rcp85_eparegion4_HadGEM2-ES_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_4e <- raster(here("data/climate_scenarios/lasso_data_4/LOCA_rcp85_eparegion4_inmcm4_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_4f <- raster(here("data/climate_scenarios/lasso_data_4/LOCA_rcp85_eparegion4_MPI-ESM-MR_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_4g <- raster(here("data/climate_scenarios/lasso_data_4/LOCA_rcp85_eparegion4_MRI-CGCM3_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr4_stack <- stack(pr_4a, pr_4b, pr_4c, pr_4d, pr_4e, pr_4f, pr_4g) # Put all pr rasters in a stack

pr4_raster_avg <- calc(pr4_stack, mean) #avg all climate models to generate 1 "mean" raster layer

### temp rasters region 4 ###########################

temp_4a <- raster(here("data/climate_scenarios/lasso_data_4/LOCA_rcp85_eparegion4_FGOALS-g2_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_4b <- raster(here("data/climate_scenarios/lasso_data_4/LOCA_rcp85_eparegion4_GFDL-CM3_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_4c <- raster(here("data/climate_scenarios/lasso_data_4/LOCA_rcp85_eparegion4_HadGEM2-CC_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_4d <- raster(here("data/climate_scenarios/lasso_data_4/LOCA_rcp85_eparegion4_HadGEM2-ES_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_4e <- raster(here("data/climate_scenarios/lasso_data_4/LOCA_rcp85_eparegion4_inmcm4_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_4f <- raster(here("data/climate_scenarios/lasso_data_4/LOCA_rcp85_eparegion4_MPI-ESM-MR_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_4g <- raster(here("data/climate_scenarios/lasso_data_4/LOCA_rcp85_eparegion4_MRI-CGCM3_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp4_stack <- stack(temp_4a, temp_4b, temp_4c, temp_4d, temp_4e, temp_4f, temp_4g) # Put all pr rasters in a stack

temp4_raster_avg <- calc(temp4_stack, mean) #avg all climate models to generate 1 "mean" raster layer



### precip rasters region 5 ###########################

pr_5a <- raster(here("data/climate_scenarios/lasso_data_5/LOCA_rcp85_eparegion5_ACCESS1-0_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_5b <- raster(here("data/climate_scenarios/lasso_data_5/LOCA_rcp85_eparegion5_CMCC-CMS_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_5c <- raster(here("data/climate_scenarios/lasso_data_5/LOCA_rcp85_eparegion5_GFDL-CM3_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_5d <- raster(here("data/climate_scenarios/lasso_data_5/LOCA_rcp85_eparegion5_GFDL-ESM2M_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_5e <- raster(here("data/climate_scenarios/lasso_data_5/LOCA_rcp85_eparegion5_GISS-E2-R_r2i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_5f <- raster(here("data/climate_scenarios/lasso_data_5/LOCA_rcp85_eparegion5_inmcm4_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_5g <- raster(here("data/climate_scenarios/lasso_data_5/LOCA_rcp85_eparegion5_IPSL-CM5A-MR_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_5h <- raster(here("data/climate_scenarios/lasso_data_5/LOCA_rcp85_eparegion5_MIROC-ESM_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_5i <- raster(here("data/climate_scenarios/lasso_data_5/LOCA_rcp85_eparegion5_MIROC-ESM-CHEM_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_5j <- raster(here("data/climate_scenarios/lasso_data_5/LOCA_rcp85_eparegion5_MRI-CGCM3_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))


pr5_stack <- stack(pr_5a, pr_5b, pr_5c, pr_5d, pr_5e, pr_5f, pr_5g, pr_5h, pr_5i, pr_5j) # Put all pr rasters in a stack

pr5_raster_avg <- calc(pr5_stack, mean) #avg all climate models to generate 1 "mean" raster layer


### temp rasters region 5 ###########################

temp_5a <- raster(here("data/climate_scenarios/lasso_data_5/LOCA_rcp85_eparegion5_ACCESS1-0_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_5b <- raster(here("data/climate_scenarios/lasso_data_5/LOCA_rcp85_eparegion5_CMCC-CMS_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_5c <- raster(here("data/climate_scenarios/lasso_data_5/LOCA_rcp85_eparegion5_GFDL-CM3_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_5d <- raster(here("data/climate_scenarios/lasso_data_5/LOCA_rcp85_eparegion5_GFDL-ESM2M_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_5e <- raster(here("data/climate_scenarios/lasso_data_5/LOCA_rcp85_eparegion5_GISS-E2-R_r2i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_5f <- raster(here("data/climate_scenarios/lasso_data_5/LOCA_rcp85_eparegion5_inmcm4_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_5g <- raster(here("data/climate_scenarios/lasso_data_5/LOCA_rcp85_eparegion5_IPSL-CM5A-MR_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_5h <- raster(here("data/climate_scenarios/lasso_data_5/LOCA_rcp85_eparegion5_MIROC-ESM_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_5i <- raster(here("data/climate_scenarios/lasso_data_5/LOCA_rcp85_eparegion5_MIROC-ESM-CHEM_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_5j <- raster(here("data/climate_scenarios/lasso_data_5/LOCA_rcp85_eparegion5_MRI-CGCM3_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp5_stack <- stack(temp_5a, temp_5b, temp_5c, temp_5d, temp_5e, temp_5f, temp_5g, temp_5h, temp_5i, temp_5j) # Put all pr rasters in a stack

temp5_raster_avg <- calc(temp5_stack, mean) #avg all climate models to generate 1 "mean" raster layer
                 

### precip rasters region 6 ###########################

pr_6a <- raster(here("data/climate_scenarios/lasso_data_6/LOCA_rcp85_eparegion6_ACCESS1-3_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_6b <- raster(here("data/climate_scenarios/lasso_data_6/LOCA_rcp85_eparegion6_HadGEM2-ES_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_6c <- raster(here("data/climate_scenarios/lasso_data_6/LOCA_rcp85_eparegion6_inmcm4_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_6d <- raster(here("data/climate_scenarios/lasso_data_6/LOCA_rcp85_eparegion6_IPSL-CM5A-MR_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_6e <- raster(here("data/climate_scenarios/lasso_data_6/LOCA_rcp85_eparegion6_MIROC-ESM-CHEM_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))
    
pr6_stack <- stack(pr_6a, pr_6b, pr_6c, pr_6d, pr_6e) # Put all pr rasters in a stack

pr6_raster_avg <- calc(pr6_stack, mean) #avg all climate models to generate 1 "mean" raster layer
                 

### temp rasters region 6 ###########################

temp_6a <- raster(here("data/climate_scenarios/lasso_data_6/LOCA_rcp85_eparegion6_ACCESS1-3_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_6b <- raster(here("data/climate_scenarios/lasso_data_6/LOCA_rcp85_eparegion6_HadGEM2-ES_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_6c <- raster(here("data/climate_scenarios/lasso_data_6/LOCA_rcp85_eparegion6_inmcm4_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_6d <- raster(here("data/climate_scenarios/lasso_data_6/LOCA_rcp85_eparegion6_IPSL-CM5A-MR_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_6e <- raster(here("data/climate_scenarios/lasso_data_6/LOCA_rcp85_eparegion6_MIROC-ESM-CHEM_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))
    
temp6_stack <- stack(temp_6a, temp_6b, temp_6c, temp_6d, temp_6e) # Put all pr rasters in a stack

temp6_raster_avg <- calc(temp6_stack, mean) #avg all climate models to generate 1 "mean" raster layer
                 
### precip rasters region 7 ###########################

pr_7a <- raster(here("data/climate_scenarios/lasso_data_7/LOCA_rcp85_eparegion7_ACCESS1-0_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_7b <- raster(here("data/climate_scenarios/lasso_data_7/LOCA_rcp85_eparegion7_EC-EARTH_r2i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_7c <- raster(here("data/climate_scenarios/lasso_data_7/LOCA_rcp85_eparegion7_GFDL-CM3_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_7d <- raster(here("data/climate_scenarios/lasso_data_7/LOCA_rcp85_eparegion7_HadGEM2-ES_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_7e <- raster(here("data/climate_scenarios/lasso_data_7/LOCA_rcp85_eparegion7_inmcm4_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_7f <- raster(here("data/climate_scenarios/lasso_data_7/LOCA_rcp85_eparegion7_MIROC-ESM-CHEM_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_7g <- raster(here("data/climate_scenarios/lasso_data_7/LOCA_rcp85_eparegion7_MRI-CGCM3_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_7h <- raster(here("data/climate_scenarios/lasso_data_7/LOCA_rcp85_eparegion7_GFDL-ESM2M_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_7i <- raster(here("data/climate_scenarios/lasso_data_7/LOCA_rcp85_eparegion7_IPSL-CM5A-MR_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr7_stack <- stack(pr_7a, pr_7b, pr_7c, pr_7d, pr_7e, pr_7f, pr_7g, pr_7h, pr_7i) # Put all pr rasters in a stack

pr7_raster_avg <- calc(pr7_stack, mean) #avg all climate models to generate 1 "mean" raster layer

### temp rasters region 8 ############################

temp_7a <- raster(here("data/climate_scenarios/lasso_data_7/LOCA_rcp85_eparegion7_ACCESS1-0_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_7b <- raster(here("data/climate_scenarios/lasso_data_7/LOCA_rcp85_eparegion7_EC-EARTH_r2i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_7c <- raster(here("data/climate_scenarios/lasso_data_7/LOCA_rcp85_eparegion7_GFDL-CM3_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_7d <- raster(here("data/climate_scenarios/lasso_data_7/LOCA_rcp85_eparegion7_HadGEM2-ES_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_7e <- raster(here("data/climate_scenarios/lasso_data_7/LOCA_rcp85_eparegion7_inmcm4_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_7f <- raster(here("data/climate_scenarios/lasso_data_7/LOCA_rcp85_eparegion7_MIROC-ESM-CHEM_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_7g <- raster(here("data/climate_scenarios/lasso_data_7/LOCA_rcp85_eparegion7_MRI-CGCM3_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_7h <- raster(here("data/climate_scenarios/lasso_data_7/LOCA_rcp85_eparegion7_GFDL-ESM2M_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_7i <- raster(here("data/climate_scenarios/lasso_data_7/LOCA_rcp85_eparegion7_IPSL-CM5A-MR_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp7_stack <- stack(temp_7a, temp_7b, temp_7c, temp_7d, temp_7e, temp_7f, temp_7g) # Put all temp rasters in a stack

temp7_raster_avg <- calc(temp7_stack, mean) #avg all climate models to generate 1 "mean" raster layer


### precip rasters region 8 ###########################

pr_8a <- raster(here("data/climate_scenarios/lasso_data_8/LOCA_rcp85_eparegion8_ACCESS1-0_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_8b <- raster(here("data/climate_scenarios/lasso_data_8/LOCA_rcp85_eparegion8_EC-EARTH_r2i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_8c <- raster(here("data/climate_scenarios/lasso_data_8/LOCA_rcp85_eparegion8_GFDL-CM3_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_8d <- raster(here("data/climate_scenarios/lasso_data_8/LOCA_rcp85_eparegion8_HadGEM2-AO_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_8e <- raster(here("data/climate_scenarios/lasso_data_8/LOCA_rcp85_eparegion8_inmcm4_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_8f <- raster(here("data/climate_scenarios/lasso_data_8/LOCA_rcp85_eparegion8_MIROC-ESM-CHEM_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_8g <- raster(here("data/climate_scenarios/lasso_data_8/LOCA_rcp85_eparegion8_MRI-CGCM3_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr8_stack <- stack(pr_8a, pr_8b, pr_8c, pr_8d, pr_8e, pr_8f, pr_8g) # Put all pr rasters in a stack

pr8_raster_avg <- calc(pr8_stack, mean) #avg all climate models to generate 1 "mean" raster layer

### temp rasters region 8 ############################

temp_8a <- raster(here("data/climate_scenarios/lasso_data_8/LOCA_rcp85_eparegion8_ACCESS1-0_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_8b <- raster(here("data/climate_scenarios/lasso_data_8/LOCA_rcp85_eparegion8_EC-EARTH_r2i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_8c <- raster(here("data/climate_scenarios/lasso_data_8/LOCA_rcp85_eparegion8_GFDL-CM3_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_8d <- raster(here("data/climate_scenarios/lasso_data_8/LOCA_rcp85_eparegion8_HadGEM2-AO_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_8e <- raster(here("data/climate_scenarios/lasso_data_8/LOCA_rcp85_eparegion8_inmcm4_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_8f <- raster(here("data/climate_scenarios/lasso_data_8/LOCA_rcp85_eparegion8_MIROC-ESM-CHEM_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_8g <- raster(here("data/climate_scenarios/lasso_data_8/LOCA_rcp85_eparegion8_MRI-CGCM3_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp8_stack <- stack(temp_8a, temp_8b, temp_8c, temp_8d, temp_8e, temp_8f, temp_8g) # Put all temp rasters in a stack

temp8_raster_avg <- calc(temp8_stack, mean) #avg all climate models to generate 1 "mean" raster layer



### precip rasters region 9 #######################

pr_9a <- raster(here("data/climate_scenarios/lasso_data_9/LOCA_rcp85_eparegion9_CanESM2_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_9b <- raster(here("data/climate_scenarios/lasso_data_9/LOCA_rcp85_eparegion9_inmcm4_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_9c <- raster(here("data/climate_scenarios/lasso_data_9/LOCA_rcp85_eparegion9_MIROC-ESM_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_9d <- raster(here("data/climate_scenarios/lasso_data_9/LOCA_rcp85_eparegion9_MIROC-ESM-CHEM_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_9e <- raster(here("data/climate_scenarios/lasso_data_9/LOCA_rcp85_eparegion9_MIROC5_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_9f <- raster(here("data/climate_scenarios/lasso_data_9/LOCA_rcp85_eparegion9_MRI-CGCM3_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr9_stack <- stack(pr_9a, pr_9b, pr_9c, pr_9d, pr_9e, pr_9f) # Put all pr rasters in a stack

pr9_raster_avg <- calc(pr9_stack, mean) #avg all climate models to generate 1 "mean" raster layer

### temp rasters region 9 ###################

temp_9a <- raster(here("data/climate_scenarios/lasso_data_9/LOCA_rcp85_eparegion9_CanESM2_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_9b <- raster(here("data/climate_scenarios/lasso_data_9/LOCA_rcp85_eparegion9_inmcm4_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_9c <- raster(here("data/climate_scenarios/lasso_data_9/LOCA_rcp85_eparegion9_MIROC-ESM_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_9d <- raster(here("data/climate_scenarios/lasso_data_9/LOCA_rcp85_eparegion9_MIROC-ESM-CHEM_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_9e <- raster(here("data/climate_scenarios/lasso_data_9/LOCA_rcp85_eparegion9_MIROC5_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_9f <- raster(here("data/climate_scenarios/lasso_data_9/LOCA_rcp85_eparegion9_MRI-CGCM3_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp9_stack <- stack(temp_9a, temp_9b, temp_9c, temp_9d, temp_9e, temp_9f) # Put all temp rasters in a stack

temp9_raster_avg <- calc(temp9_stack, mean) #avg all climate models to generate 1 "mean" raster layer


### precip rasters region 10 ###########################

pr_10a <- raster(here("data/climate_scenarios/lasso_data_10/LOCA_rcp85_eparegion10_CanESM2_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_10b <- raster(here("data/climate_scenarios/lasso_data_10/LOCA_rcp85_eparegion10_CMCC-CM_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_10c <- raster(here("data/climate_scenarios/lasso_data_10/LOCA_rcp85_eparegion10_CMCC-CMS_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_10d <- raster(here("data/climate_scenarios/lasso_data_10/LOCA_rcp85_eparegion10_HadGEM2-AO_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_10e <- raster(here("data/climate_scenarios/lasso_data_10/LOCA_rcp85_eparegion10_HadGEM2-AO_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_10f <- raster(here("data/climate_scenarios/lasso_data_10/LOCA_rcp85_eparegion10_MIROC-ESM-CHEM_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr_10g <- raster(here("data/climate_scenarios/lasso_data_10/LOCA_rcp85_eparegion10_MRI-CGCM3_r1i1p1_pr_pctchg_2041_2070_1981_2010_Annual.tif"))

pr10_stack <- stack(pr_10a, pr_10b, pr_10c, pr_10d, pr_10e, pr_10f, pr_10g) # Put all pr rasters in a stack

pr10_raster_avg <- calc(pr10_stack, mean) #avg all climate models to generate 1 "mean" raster layer

### temp rasters region 10 ############################

temp_10a <- raster(here("data/climate_scenarios/lasso_data_10/LOCA_rcp85_eparegion10_CanESM2_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_10b <- raster(here("data/climate_scenarios/lasso_data_10/LOCA_rcp85_eparegion10_CMCC-CM_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_10c <- raster(here("data/climate_scenarios/lasso_data_10/LOCA_rcp85_eparegion10_CMCC-CMS_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_10d <- raster(here("data/climate_scenarios/lasso_data_10/LOCA_rcp85_eparegion10_HadGEM2-AO_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_10e <- raster(here("data/climate_scenarios/lasso_data_10/LOCA_rcp85_eparegion10_HadGEM2-AO_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_10f <- raster(here("data/climate_scenarios/lasso_data_10/LOCA_rcp85_eparegion10_MIROC-ESM-CHEM_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp_10g <- raster(here("data/climate_scenarios/lasso_data_10/LOCA_rcp85_eparegion10_MRI-CGCM3_r1i1p1_tas_F_2041_2070_1981_2010_Annual.tif"))

temp10_stack <- stack(temp_10a, temp_10b, temp_10c, temp_10d, temp_10e, temp_10f, temp_10g) # Put all temp rasters in a stack

temp10_raster_avg <- calc(temp10_stack, mean) #avg all climate models to generate 1 "mean" raster layer


pr_raster_merge <- merge(pr10_raster_avg, pr9_raster_avg, pr8_raster_avg, pr7_raster_avg, pr6_raster_avg, pr5_raster_avg, pr4_raster_avg, pr3_raster_avg, pr2_raster_avg, pr1_raster_avg)
plot(pr_raster_merge)

temp_raster_merge <- merge(temp10_raster_avg, temp9_raster_avg, temp8_raster_avg, temp7_raster_avg, temp6_raster_avg, temp5_raster_avg, temp4_raster_avg, temp3_raster_avg, temp2_raster_avg, temp1_raster_avg)
plot(temp_raster_merge)

```



